### ISSUE TITLE
Queue Statistics

### ISSUE THREAD

**Issue by Ehesp** [redibox/job#4]
Each queue should provide stats on metrics of it's Jobs. E.g. process times, average job waiting length etc.

**Comment by Salakar** [comment]
Thinking capped lists for history with a configurable size - per queue list and then a hash per queue with stats.

**Comment by Salakar** [comment]
### Implemented:
- **Time in Queue** - time in ms a job has been waiting in a queue
  - queue avg
  - queue min
  - queue max
  - job time
- **Time to Process** - time in ms a job took to run (does not include time in queue)
  - queue avg
  - queue min
  - queue max
  - job time
- **Time to Complete** - time in ms a job took to complete (include time in queue - so creation to completion)
  - queue avg
  - queue min
  - queue max
  - job time

**Comment by Salakar** [comment]
Will create a new issue for history. Closing this as completed.
